[project]
name = "horde-openai-proxy"
version = "0.1.0"
description = ""
authors = [{ name = "Luke100000", email = "jonas.peche@aon.at" }]
requires-python = ">=3.13,<4"
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]
dependencies = [
    "cachetools",
    "transformers[sentencepiece,chat-template]",
    "httpx>=0.27.0",
    "pydantic>=2.13.4",
    "cachetools-async>=0.0.5",
]

[dependency-groups]
dev = [
    "ruff",
    "pre-commit",
    "pytest",
    "pytest-httpx>=0.30.0",
    "pytest-asyncio>=1.4.0",
]
fastapi = ["uvicorn", "fastapi[standard]"]

[build-system]
requires = ["uv_build>=0.11.26,<0.12.0"]
build-backend = "uv_build"
